
name: freezed_example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner:
  json_serializable: ^6.6.1
  freezed: ^2.3.2
dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  meta: ^1.9.0
